# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-25 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Situations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation_n', models.IntegerField()),
                ('text', models.TextField()),
                ('item_pre', models.IntegerField()),
                ('item_ano', models.IntegerField()),
                ('item_het', models.IntegerField()),
                ('item_soc', models.IntegerField()),
                ('item_sov', models.IntegerField()),
            ],
        ),
    ]
