# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-27 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20170325_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situation',
            name='text',
        ),
    ]
