# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-27 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_remove_situation_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situation',
            name='item_ano',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='situation',
            name='item_het',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='situation',
            name='item_pre',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='situation',
            name='item_soc',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='situation',
            name='item_sov',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='situation',
            name='situation_n',
            field=models.IntegerField(null=True),
        ),
    ]
