# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-27 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_auto_20170327_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situation',
            name='situation_n',
        ),
        migrations.AddField(
            model_name='situation',
            name='n',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='situation',
            name='item_ano',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='situation',
            name='item_het',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='situation',
            name='item_pre',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='situation',
            name='item_soc',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='situation',
            name='item_sov',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
