# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-27 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_auto_20170327_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='situation',
            name='user_ip',
            field=models.CharField(default=2, max_length=46),
            preserve_default=False,
        ),
    ]
