# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-28 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='score',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
