# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-28 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_item_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Situation',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_n',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='situation_n',
            field=models.IntegerField(),
        ),
    ]
