# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-05 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0010_auto_20170328_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.IntegerField()),
                ('score', models.IntegerField()),
                ('latency', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CSocionomyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.IntegerField()),
                ('score', models.IntegerField()),
                ('latency', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HeteronomyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.IntegerField()),
                ('score', models.IntegerField()),
                ('latency', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PrenomyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.IntegerField()),
                ('score', models.IntegerField()),
                ('latency', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.IntegerField()),
                ('pres', models.IntegerField()),
                ('prel', models.FloatField()),
                ('anos', models.IntegerField()),
                ('anol', models.FloatField()),
                ('hets', models.IntegerField()),
                ('hetl', models.FloatField()),
                ('socs', models.IntegerField()),
                ('socl', models.FloatField()),
                ('sovs', models.IntegerField()),
                ('sovl', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=46)),
                ('user_ip', models.CharField(max_length=46)),
            ],
        ),
        migrations.CreateModel(
            name='VSocionomyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.IntegerField()),
                ('score', models.IntegerField()),
                ('latency', models.FloatField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Subject')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='latency',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='situation',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Subject'),
        ),
        migrations.AddField(
            model_name='prenomyitem',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Subject'),
        ),
        migrations.AddField(
            model_name='heteronomyitem',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Subject'),
        ),
        migrations.AddField(
            model_name='csocionomyitem',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Subject'),
        ),
        migrations.AddField(
            model_name='anomyitem',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Subject'),
        ),
    ]
