# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-05 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_auto_20170405_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anomyitem',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='csocionomyitem',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='heteronomyitem',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='prenomyitem',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='situation',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='vsocionomyitem',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='item',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='user_ip',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='item',
            name='subject',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Subject'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AnomyItem',
        ),
        migrations.DeleteModel(
            name='CSocionomyItem',
        ),
        migrations.DeleteModel(
            name='HeteronomyItem',
        ),
        migrations.DeleteModel(
            name='PrenomyItem',
        ),
        migrations.DeleteModel(
            name='Situation',
        ),
        migrations.DeleteModel(
            name='VSocionomyItem',
        ),
    ]
