# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0015_subject_n_items'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('subject', 'situation_n', 'item_n')]),
        ),
    ]
