# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0017_auto_20170906_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='last_studies',
            field=models.CharField(blank=True, choices=[('P', 'Primaria'), ('S', 'Secundaria'), ('B', 'Bachillerato'), ('FM', 'Formación profesional media'), ('FS', 'Formación profesional superior'), ('U', 'Universidad')], max_length=46),
        ),
    ]
