# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 07:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0018_auto_20170906_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='last_studies',
            field=models.CharField(blank=True, choices=[('P', 'Primaria'), ('S', 'Secundaria'), ('B', 'Bachillerato'), ('FM', 'Formación profesional media'), ('FS', 'Formación profesional superior'), ('U', 'Universidad')], max_length=2),
        ),
    ]
