# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0022_auto_20170917_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
