# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0023_auto_20170917_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='first_time',
            field=models.BooleanField(default=True),
        ),
    ]
