# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 18:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0024_subject_first_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='life_satisfaction',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='current_country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='subject',
            name='home_country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
