# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0025_auto_20170928_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='current_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='home_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='life_satisfaction',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
    ]
