# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 19:17
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0026_auto_20170928_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='current_country',
            field=django_countries.fields.CountryField(blank=True, default='España', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='home_country',
            field=django_countries.fields.CountryField(blank=True, default='España', max_length=2),
            preserve_default=False,
        ),
    ]
