# -*- coding: utf-8 -*-

situations = {
    0: "He cogido una fuerte gripe que apenas me permite levantarme de la cama.",
    1: "Tengo una cita importante y en el camino ocurre un accidente que me retrasa.",
    2: "Inesperadamente me comunican que hoy tengo el día libre. ¿Qué hago?",
    3: "Cuando he tomado decisiones sobre qué estudiar o trabajar.",
    4: "Hay que hacer limpieza y ordenar la casa...",
    5: "Esta tarde tengo dos horas libres, pero un amigo me pide un favor.",
    6: "Cuando he tenido dificultades y me he enfrentado a decisiones importantes...",
    7: "Cuando me toca hacer la comida...",
    8: "Me ha tocado la lotería y he ganado una importante cantidad de dinero, ¿qué pienso?",
    9: "Hoy hay huelga y se ha convocado una manifestación.",
    10: "Una persona próxima comienza a explicarme sus problemas.",
    11: "Mi vida tiene sentido cuando…",
}


items = {
    0: ["Me dejo cuidar.",
        "Intento hacer algo que me guste, aunque me impida descansar.",
        "Me siento culpable por no poder cumplir con mis deberes/obligaciones.",
        "Me preocupa que esto pueda provocar que alguien se enfade o se moleste.",
        "Me preocupa dejar desatendidos a mis seres queridos."],
    1: ["Me desespero pensando en mi mala suerte.",
        "Me enfado y pienso en los culpables de que llegue tarde.",
        "Siempre voy con tiempo, para no llegar tarde.",
        "Me preocupa llegar tarde, por si se enfadan conmigo.",
        "Me quedo preocupado, pensando en las personas que también se han visto afectadas por el accidente."],
    2: ["Voy dejando pasar el día sin hacer nada en concreto.",
        "Rápidamente encuentro un montón de cosas apasionantes que me gustaría hacer.",
        "Lo primero que hago es organizar el día, elaboro un plan.",
        "Pienso en mis amigos y a quién podría llamar para quedar.",
        "Aprovecho para estar con los míos, siempre hay cosas que puedo hacer por ellos."],
    3: ["No he tenido que tomar estas decisiones u otros las han tomado por mí.",
        "Siempre he priorizado lo que me gustaba.",
        "He escogido en función del éxito que pudiera tener.",
        "He escogido según lo que opinaban o hacían mis amigos.",
        "He escogido en función de los horarios y/o el sueldo, pensando en lo mejor para mi familia"],
    4: ["Se me hace cuesta arriba, me siento sin energía.",
        "Hago lo imprescindible, priorizo lo mío.",
        "Limpio todo a conciencia, me molesta el desorden y/o la falta de limpieza.",
        "Si tengo una visita, me esmero ordenando y limpiando para que se sienta a gusto.",
        "Me encargo de hacer lo mío y lo de los demás."],
    5: ["Qué pereza, había pensado quedarme en casa y no hacer nada.",
        "Me molesta que me lo pida, prefiero dedicar la tarde a algo divertido.",
        "No me gusta improvisar de ese modo, ya lo tenía todo organizado.",
        "Estoy contento de que me lo pida, me gusta ayudar a los amigos.",
        "Me siento culpable si dedico tiempo a un amigo en detrimento de la pareja o la familia."],
    6: ["He tenido la sensación de que todo me superaba.",
        "Me lo he pensado poco y he actuado rápido.",
        "Me he quedado pensado mucho, dando vueltas al asunto antes de tomar una decisión.",
        "He estado muy pendiente de la aprobación de la gente de mi entorno.",
        "He tomado decisiones importantes más en beneficio de los míos que de mi."],
    7: ["No sé qué cocinar, me cuesta.",
        "No lo suelo pensar con antelación, improviso.",
        "Lo tengo pensado y/o preparado con antelación.",
        "Me esmero sólo en situaciones especiales, cuando hay invitados.",
        "En mi casa miro que todos queden satisfechos, aunque tenga que cocinar para cada uno."],
    8: ["Pienso en alguien que me pueda ayudar a gestionar el dinero. ",
        "Pienso gastar el dinero en hacer todas aquellas cosas que me diviertan.",
        "Pienso en ahorrar, invertir o pagar deudas.",
        "Pienso en comprar cosas de valor (un coche de gama alta, ropa de marca, joyas…).",
        "Pienso en cómo ayudar a los míos."],
    9: ["Me quedo en casa sin hacer planes.",
        "Aprovecho el día para hacer lo que me gusta.",
        "Me posiciono con fuerza según mis principios, a favor o en contra.",
        "Hago lo que vayan a hacer mis compañeros.",
        "Pienso en mi familia/pareja y hago lo que mejor sea para ellos."],
    10: ["Aprovecho para compartir también mis problemas.",
         "Intento ver lo positivo de lo que me cuenta.",
         "Le explico lo que debería hacer para solucionarlo.",
         "Le digo lo que quiere escuchar para que se sienta bien. ",
         "Hago míos sus problemas."],
    11: ["Me cuesta encontrarle sentido.",
         "Disfruto de los placeres de la vida.",
         "Tengo un proyecto profesional/intelectual.",
         "Tengo buenos amigos que me aprecian y me solicitan.",
         "Estoy cerca de mi familia y/o mi pareja."],
}
